### ISSUE TITLE
Frontend view?

### ISSUE THREAD

**Issue by frozseven** [JayVora-SerpentCS/hotelmgmt_v8#10]
Hi,
Am wondering about the frontend? at the moment this works fine for the backend but how does guest book their rooms from the website frontend?

**Comment by frozseven** [comment]
Is there a way to get the details from the frontend. From the website end of Odoo? Especially the date selection. How can i get that?

**Comment by JayVora-SerpentCS** [comment]
@frozseven We are right now working on this. We shall push once we reach to a satisfactory level.
Are you in plan to contribute? or you want to get the ready system?
We can professionally help you in order to achieve your aim.
Thanks.
