### ISSUE TITLE
 Room does not charge for quick reservation odoo V10

### ISSUE THREAD

**Issue by camilozuluaga** [JayVora-SerpentCS/hotelmgmt_v8#101]
Hello to all good day and many thanks in advance for the attention.

At the moment of making a reservation from the summary when clicking on an available room, in the part of fast reservation is not automatically loading the room of which corresponds the cell of the selected table.
<img width="649" alt="1" src="https://cloud.githubusercontent.com/assets/2817796/25600634/495645d0-2eab-11e7-81f9-4a86ff4d5b35.PNG">
<img width="734" alt="2" src="https://cloud.githubusercontent.com/assets/2817796/25600636/4af6f984-2eab-11e7-929a-0d2614ec8b16.PNG">

**Comment by camilozuluaga** [comment]
@JayVora-SerpentCS help me pleace.

**Comment by JayVora-SerpentCS** [comment]
sure, we will take a look at it soon.
Are you working on any implementation?

**Comment by camilozuluaga** [comment]
@JayVora-SerpentCS 
I am doing some tests to implement the modules, now I was doing some tests and it is something very curious because in a room I am doing tests that I have occupied in that if I load the number in the field room_id, but in the other rooms Is appearing Then it is very confusing. I appreciate your collaboration.

<img width="959" alt="4" src="https://cloud.githubusercontent.com/assets/2817796/25705160/f8ab9a7e-30a1-11e7-972a-95d789ed070e.PNG">
<img width="960" alt="3" src="https://cloud.githubusercontent.com/assets/2817796/25705161/f8b1ed0c-30a1-11e7-95fa-9a5a72eeff5b.PNG">
<img width="960" alt="2" src="https://cloud.githubusercontent.com/assets/2817796/25705163/f8b567ca-30a1-11e7-9f98-200c09000682.PNG">
<img width="960" alt="1" src="https://cloud.githubusercontent.com/assets/2817796/25705162/f8b281d6-30a1-11e7-8764-8f106498e133.PNG">

**Comment by BrayhanJaramillo** [comment]
I have the same error, can you help me please? 

What can i do to fix the error? 

I would appreciate your help

**Comment by JayVora-SerpentCS** [comment]
@krishnaprajapati16894 please check.

**Comment by BrayhanJaramillo** [comment]
What I check @ krishnaprajapati16894 ?

**Comment by JayVora-SerpentCS** [comment]
We have a PR #98 which will solve the said issue, thanks.
