### ISSUE TITLE
System cannot show price when checkin.

### ISSUE THREAD

**Issue by 360org** [JayVora-SerpentCS/hotelmgmt_v8#103]
Hello i need help. 
i have install success full but when i try to check in and check out, the hotel room not show up price

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello 
In hotel reservation --> After add check-in date and check-out date then also add room when open a pop up for add room that shows the room price.Here you can see this.
![hotelprice](https://cloud.githubusercontent.com/assets/23502495/25987060/0b23eb9c-3710-11e7-8fe9-4590a2756d51.png)
Please elaborate your query.

**Comment by 360org** [comment]
you can check, it i have setup rom price, and al configuration ok, but when checkin & check out, there are nothing in the bill.
![image](https://cloud.githubusercontent.com/assets/8590556/25988742/5e8acd6a-3723-11e7-90b4-bd7b23bfccc7.png)

![image](https://cloud.githubusercontent.com/assets/8590556/25988718/3f69dfac-3723-11e7-8b6c-7ed040ec827a.png)

![image](https://cloud.githubusercontent.com/assets/8590556/25988691/225be25c-3723-11e7-8423-2571e19b0a6c.png)

**Comment by W360S** [comment]
[<iframe width="560" height="315" src="https://www.youtube.com/embed/tznSGbUIlXg" frameborder="0" allowfullscreen></iframe>](url)

**Comment by 360org** [comment]
https://www.youtube.com/embed/tznSGbUIlXg
here is the error in video

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello 
You can check Room with its price in Hotel Room
![room1](https://cloud.githubusercontent.com/assets/23502495/25992293/c65128ea-3723-11e7-9f1d-29bd1c6b719e.png)
Also, check room and its price in hotel folio
![room3](https://cloud.githubusercontent.com/assets/23502495/25992381/edd8c4e0-3723-11e7-96ed-4340233270c6.png)

**Comment by 360org** [comment]
The problems from e is the room already set price, but when i checkin it show up 0, that mean price =0, plz check the image ![image](https://cloud.githubusercontent.com/assets/8590556/25992529/feccdff4-3730-11e7-97d3-07f815d7a791.png)

**Comment by 360org** [comment]
plz check from my end: http://demo-khachsan.w360s.com.vn/
user/pass: demo/demo, no worry about credential, i will be deleted demo en few days

**Comment by JayVora-SerpentCS** [comment]
This has been fixed in recent pushes. Do check and revert if the issue still persists.
