### ISSUE TITLE
Question: Where Do I select the folio or the room in the POS

### ISSUE THREAD

**Issue by AizenL** [JayVora-SerpentCS/hotelmgmt_v8#108]
Hi, please I dont know where to select the folio or the room in the POS.

Please some guide.

![2017-06-07_4-16-23](https://user-images.githubusercontent.com/8664487/26871267-41ae2c40-4b38-11e7-9d04-36b5795f9537.png)

**Comment by JayVora-SerpentCS** [comment]
Its feature our team is developing internally. You may send an email to our team contact@serpentcs.com if you need the solution on priority basis, we will be happy to assist.

**Comment by fraharijaona** [comment]
Please, any clue to this issue?

**Comment by JayVora-SerpentCS** [comment]
Can you check with latest code?
