### ISSUE TITLE
reservation Rooms don't use price list

### ISSUE THREAD

**Issue by dceevp** [JayVora-SerpentCS/hotelmgmt_v8#110]
Hi, 

I have a problem with Odoo 9.0 and Hotel management System V9.0.
I have a price list for each room category, but on reservation and create folio from reservation, the system only use de base price  instead the price in price list.

Could you help me where i can modified the code to resolve this?

thanks

I add some images

Pricelist (set room to $70, base price for room 35 000 local currency)

![pricelist](https://user-images.githubusercontent.com/9794846/27559712-d0d39400-5a7e-11e7-8b01-f5a26ab6f600.PNG)

Info on reservation room

![reservation](https://user-images.githubusercontent.com/9794846/27559758-f6359018-5a7e-11e7-8c23-84ad0eb49659.PNG)

![folio1](https://user-images.githubusercontent.com/9794846/27559774-027a8586-5a7f-11e7-8095-6a010a11c0e8.PNG)

![folio2](https://user-images.githubusercontent.com/9794846/27559782-0d7e6f24-5a7f-11e7-825f-4e1647e68f53.PNG)

Nice App :D

**Comment by dceevp** [comment]
hi....
i look arround others files and  i think so maybe like this on file hotel_reservation.py line 414

'price_unit': self.pool.get('product.pricelist').price_get(self._cr, self._uid, [reservation.pricelist_id], r.product_id.id, 1, reservation.partner_id)[reservation.pricelist_id],

But, i get the following error

File "/odoo/odoo-server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ValueError: "can't adapt type 'product.pricelist'" while evaluating
u'_create_folio()'

could anyone help me?

**Comment by JayVora-SerpentCS** [comment]
@dceevp We will check this today itself and shall respond back.

**Comment by dceevp** [comment]
Hi,
Thanks for reply

I found a solution, i don't know if this is the best, but it's work for me.
On hotel_reservation.py I add the following code, Line 411, 

![captura](https://user-images.githubusercontent.com/9794846/27691220-a002db1e-5ca0-11e7-8d65-5b7441eadc88.PNG)


Now, the reservation room use my pricelist

Pricelist
![1](https://user-images.githubusercontent.com/9794846/27690741-642bdb82-5c9f-11e7-8807-41135107c818.PNG)

reservation line with local amount
![2](https://user-images.githubusercontent.com/9794846/27690778-7a31a768-5c9f-11e7-836b-4281f48dde31.PNG)

hotel folio with price fixed
![3](https://user-images.githubusercontent.com/9794846/27690794-888abafc-5c9f-11e7-8ae6-82c5575db925.PNG)

Folio details
![4](https://user-images.githubusercontent.com/9794846/27690813-9717e630-5c9f-11e7-928f-9574b7c29f6a.PNG)


Sales and invoice work fine.
