### ISSUE TITLE
Duration in Days	in set with '0' when save record

### ISSUE THREAD

**Issue by Vishal-Mak** [JayVora-SerpentCS/hotelmgmt_v8#114]
Hello,
Create New Folio, filled required fields, 'Duration in Days' is calculated as per date range 
but when save record, Duration in Days	set with '0' value.

Reason : If duration field is calculated and its property is readonly=True then odoo will not store value in database.

**Comment by JayVora-SerpentCS** [comment]
#115 fixed it, thanks.
