### ISSUE TITLE
Calculation of Duration in Days	

### ISSUE THREAD

**Issue by Vishal-Mak** [JayVora-SerpentCS/hotelmgmt_v8#120]
Hello,

If Folio is generated from another action, duration days is not calculated.
For example:  Create Folio from Reservation, click 'Generate Folio' menu and check created Folio.

Following is wishlist :
Create Folio from reservation should redirect to 'Generate Folio' action

**Comment by JayVora-SerpentCS** [comment]
It has been pushed in latest commit.
