### ISSUE TITLE
Create Room Status 

### ISSUE THREAD

**Issue by waiyao-onnet** [JayVora-SerpentCS/hotelmgmt_v8#121]
Hi, just spot that Room's Status while creating room, the letters inside the status bar became ninja. 

![image](https://user-images.githubusercontent.com/30222371/29597238-e4bf43cc-87f3-11e7-8ee8-25c2b1057ac0.png)

**Comment by JayVora-SerpentCS** [comment]
We will check soon. @krishnaprajapati16894
