### ISSUE TITLE
Stuck In "Draft Quotation"

### ISSUE THREAD

**Issue by waiyao-onnet** [JayVora-SerpentCS/hotelmgmt_v8#122]
Hi, I after create a reservation, I go to generate Folio "create Folio", noticed that after I generated Invoice and then click on "cancel" button will make the Folio status to "Cancelled", then "Set to Draft", then there is nothing will happen by clicking on "Confirm Folio" or "Cancel Folio" and the Folio will remain in Draft Quotation. 

I also try to change the status from Postgres but can't find the attribute "state" for folio attribute, I would like request a user guide for using this system or if there others way to fix this problem.

![image](https://user-images.githubusercontent.com/30222371/29605294-e9ec8782-881c-11e7-859a-3b660ea2311f.png)
 
![image](https://user-images.githubusercontent.com/30222371/29605350-1bc99970-881d-11e7-913b-9d87aa7928a0.png)

**Comment by JayVora-SerpentCS** [comment]
@GitChungWY we will check soon.

**Comment by waiyao-onnet** [comment]
Thanks alot :) @JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
Fixed in latest push.

**Comment by waiyao-onnet** [comment]
Sorry @JayVora-SerpentCS I forgot to mention most of the issue I post is from version 8.0, hope branch 8.0 will be fix as well. 

Thanks for your efforts.

**Comment by JayVora-SerpentCS** [comment]
@krishnaprajapati16894 please check.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
I solved this issues in version 8.0

**Comment by waiyao-onnet** [comment]
Thanks alot  😁, Appreciated
