### ISSUE TITLE
Regarding importing this module

### ISSUE THREAD

**Issue by sweetyshetty08** [JayVora-SerpentCS/hotelmgmt_v8#142]
It is not clear how to deploy or run this module on odoo.Can you please help? It is very urgent

**Comment by JayVora-SerpentCS** [comment]
You may contact to contact@serpentcs.com

**Comment by JayVora-SerpentCS** [comment]
This is a simple set of useful modules to be added to your addons path.

**Comment by sweetyshetty08** [comment]
Thank you! :)
