### ISSUE TITLE
Overall issues with hotel management module

### ISSUE THREAD

**Issue by supersimplesofty** [JayVora-SerpentCS/hotelmgmt_v8#16]
Hi,  
For reservations, Status of rooms gets changed automatically after a while. Same room assigned twice which is occupied.
For housekeeping services,
No list of activities displayed. Showing Integrity error while adding and creating activities.
For restaurant tab,
After confirmation on clicking button to creates orders creating records repeatedly after creating one for same table reservation.  After confirmation of orders on clicking 'Generate KOT' creating repeated records in KOT on each click for same order.
In orders, for selecting waiter name listed out customers name. Same for table order and KOT.
For restaurant there is no generation of invoice for all charges consumed by customers from hotel or from outside individual.

**Comment by MalayKhamar-SerpentCS** [comment]
@supersimplesofty 
Please try out with the latest code from here.
https://github.com/khamarmalay/hotelmgmt_v8/tree/8.0
we are still working on it.
Thanks,
