### ISSUE TITLE
Error while installing module

### ISSUE THREAD

**Issue by Shubhadap** [JayVora-SerpentCS/hotelmgmt_v8#18]
At first we installed hotel management from the zip file and everything automatically shows installed but nothing can be seen under hotel management tab except Folio and folio reports.

**Comment by MalayKhamar-SerpentCS** [comment]
@Shubhadap
Please try out with the latest code from here.
https://github.com/khamarmalay/hotelmgmt_v8/tree/8.0
we are still working on it.
Thanks,
