### ISSUE TITLE
Unable to create invoice for restaraunt 

### ISSUE THREAD

**Issue by Shubhadap** [JayVora-SerpentCS/hotelmgmt_v8#19]
I have V8 for Hotel Management. I am unable to create Invoice for restaurant. Please help me with this issue.

**Comment by MalayKhamar-SerpentCS** [comment]
@Shubhadap
Please try out with the latest code from here.
https://github.com/khamarmalay/hotelmgmt_v8/tree/8.0
 we are still working on it.
Thanks,

**Comment by JayVora-SerpentCS** [comment]
@Shubhadap It has been merged here now, so latest pull should close this.
