### ISSUE TITLE
Is it normal that this repo is not a fork from OCA?

### ISSUE THREAD

**Issue by flotho** [JayVora-SerpentCS/hotelmgmt_v8#21]
Hi @JayVora-SerpentCS 

Is it normal that this part of your work still "off" from the OCA repos? You used to be a great contributor on those repo.
Didi you planned to merge your work in the OCA vertical hotel?
Thanks

**Comment by JayVora-SerpentCS** [comment]
@flotho Hotel modules existed from us way before OCA's inception!
I have already created a PR for OCA vertical hotel, but as the diff is huge, reviewers have the difficulties.

**Comment by flotho** [comment]
Hi @JayVora-SerpentCS 
A great thanks for your answer. I see clearly now the rain is gone.... ;-)

**Comment by JayVora-SerpentCS** [comment]
We will plan to pull module by module, and vertical-hotel should be closed.
