### ISSUE TITLE
additional_hours does not exist

### ISSUE THREAD

**Issue by lvx5013** [JayVora-SerpentCS/hotelmgmt_v8#22]
Hi, thanks for the repo. When I tried to install, i got "additional_hours" does not exist error. I checked the code, it was defined in your hotel.py, however it might be some issue with referencing the code?

ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `additional_hours` does not exist

Error context:
View `res.company.inherit.config.hotel`
[view_id: 1920, xml_id: n/a, model: res.company, parent_id: 111]" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/hotel/views/hotel_view.xml:13, near
<record model="ir.ui.view" id="res_company_inherit_config_hotel">
			<field name="name">res.company.inherit.config.hotel</field>
			<field name="model">res.company</field>
			<field name="inherit_id" ref="base.view_company_form"/>
			<field name="arch" type="xml">
				<xpath expr="//field[@name='currency_id']" position="after">
					<field name="additional_hours"/>
				</xpath>
			</field>
		</record>

**Comment by khamarmalay** [comment]
@lvx5013  Please try out with the latest code from here.
https://github.com/JayVora-SerpentCS/hotelmgmt_v8/tree/8.0
Thanks,

**Comment by lvx5013** [comment]
Thank you! Work like a charm, wonderful module, I ll keep developing it, if there's an opportunity for partnership,would you consider?

**Comment by lvx5013** [comment]
Thank you ! Work like a charm, I ll try to develop it and make it more business friendly @khamarmalay

**Comment by JayVora-SerpentCS** [comment]
@lvx5013, thanks for the feedback! We appreciate!
Lets meet on jay.vora@serpentcs.com We have contributed this for community.
Like others, you may also donate!
