### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by jeansilver** [JayVora-SerpentCS/hotelmgmt_v8#23]
Hello,

During installation of Hotel module I got this error : 

Error details:
Field `uos_id` does not exist

Error context:
View `hotel.room.form`
[view_id: 960, xml_id: n/a, model: hotel.room, parent_id: n/a]" while parsing file:///D:/odoo8/odoo_8/addons_costum/hotel/views/hotel_view.xml:294, near

How I can fix that please, thank you in advance

Best regards,

**Comment by JayVora-SerpentCS** [comment]
@jeansilver Did you try master branch or 8.0?

**Comment by jeansilver** [comment]
8.0

**Comment by JayVora-SerpentCS** [comment]
@jeansilver it works normal here!
Make sure you are not using odoo v9! Odoo v8 already has uos_id!

**Comment by jeansilver** [comment]
Yes I'm using Odoo 8, but still the same problem, I think the option " delegate= True " in the model 'hotel.room' :     product_id = fields.Many2one('product.product', 'Product_id',
                                 required=True, delegate=True,
                                 ondelete='cascade') 
doesn't work in the view side, uos_id attribute is in the table 'product.product'.

**Comment by SerpentCS** [comment]
**@jeansilver** The code works at our end when we are using Odoo v8 source code.

Just to make sure, please run the command **git branch** to check the current branch for odoo repository.
