### ISSUE TITLE
Cant see Pos Orders in Folio

### ISSUE THREAD

**Issue by iamtutumo** [JayVora-SerpentCS/hotelmgmt_v8#25]
![pos orders](https://cloud.githubusercontent.com/assets/7942491/10337706/46a9e332-6d0a-11e5-9b87-88db144d275d.PNG)
![folio](https://cloud.githubusercontent.com/assets/7942491/10337712/4d5a3f74-6d0a-11e5-926f-33aac7732163.PNG)

i cant seem to find the pos orders made from point of sale using the customers name after putting the folio number 
please help

**Comment by MalayKhamar-SerpentCS** [comment]
@muguli22 
You are created Pos order for Folio/00002, So pos order details was created in Folio/00002 
not in Folio/00001.
Thanks

**Comment by mariusmarolla** [comment]
Hi!
I confirm there's a problem with viewing pos orders in folio... Perhaps in the first post muguli22 has just published the wrong images... 
![1](https://cloud.githubusercontent.com/assets/7656042/10640153/ba6ada4c-7813-11e5-934a-b5d22bed714a.png)
![2](https://cloud.githubusercontent.com/assets/7656042/10640160/c592b5c0-7813-11e5-9533-e96d2149ce36.png)
Of course the same problem occurs when generating a POS Order Report in the Hotel Management Reporting Section...
Hope you have an idea about to face this :+1:

**Comment by MalayKhamar-SerpentCS** [comment]
@mariusmarolla 
Pos order not show in folio when it is in draft state.Once you make payment and pos order goes to paid state it will visible in folio.
Thanks

**Comment by SerpentCS** [comment]
@**mariusmarolla**
![2](https://cloud.githubusercontent.com/assets/13119902/11027969/5f7b2d4a-86e0-11e5-9aa7-64e71c8ff834.png)

Here we have the **Payment** button to pay for the order. After clicking we have the following wizard:
![hotel_folio_3](https://cloud.githubusercontent.com/assets/13119902/11028044/ee8c4c58-86e0-11e5-8624-5acad732087a.png)

After the user click on the **Make Payment** the order reference will shown in the Folio as following:
![hotel_folio_4](https://cloud.githubusercontent.com/assets/13119902/11028128/b6195f54-86e1-11e5-9497-aac80ee1293e.png)

Hope this will help you!

**Comment by mariusmarolla** [comment]
Great Job! 

Going to promote a kind of hotel and restaurant verticalization here in
italy - a classical turistic land (of course with Odoo and several other
modules).... There will be an integration with a tool (suddenly not
opemsource, but at a very low cost) that tracks guests preferences and
opinions through cookies and surveys as they are "in the structure"
using hotel's wifi... 

If it works, i'm not going to forget you great contrinution! 

---
Marius Marolla
EnterSYS - Resp. Commerciale

Il 09/11/2015 01:33 SerpentCS ha scritto: 

> @MARIUSMAROLLA
> [1] 
> 
> Here we have the PAYMENT button to pay for the order. After clicking we have the following wizard:
> [2] 
> 
> After the user click on the MAKE PAYMENT the order reference will shown in the Folio as following:
> [3] 
> 
> Hope this will help you! 
> 
> --
> Reply to this email directly or view it on GitHub [4].
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/13119902/11027969/5f7b2d4a-86e0-11e5-9aa7-64e71c8ff834.png
[2]
https://cloud.githubusercontent.com/assets/13119902/11028044/ee8c4c58-86e0-11e5-8624-5acad732087a.png
[3]
https://cloud.githubusercontent.com/assets/13119902/11028128/b6195f54-86e1-11e5-9497-aac80ee1293e.png
[4]
https://github.com/JayVora-SerpentCS/hotelmgmt_v8/issues/25#issuecomment-154983062
