### ISSUE TITLE
Check In and Check Out Datetime in database is took from server it local in europe

### ISSUE THREAD

**Issue by phoxaysy** [JayVora-SerpentCS/hotelmgmt_v8#26]
Local time of server is everytime base on Europe time, What's issue:
1. Change local time of time of of country
2. Convert in python code 

Please advise

Thanks

**Comment by JayVora-SerpentCS** [comment]
Dear @phoxaysy ,
Usually, the ODOO saves every timestamp in database as GMT time.
With the parsing of web when it's displayed to browser, it is converted as per the user timezone(browser timezone as a latter priority).
So, if you want to pass some dates to DB via CODE, you must convert to GMT.
Hope this helps.
Thanks.

**Comment by JayVora-SerpentCS** [comment]
You may see latest code in v9, which shows the example of using offset.
