### ISSUE TITLE
error when installing in V9

### ISSUE THREAD

**Issue by iamtutumo** [JayVora-SerpentCS/hotelmgmt_v8#27]
Hello 
i get this error when installing in V9
![error v9](https://cloud.githubusercontent.com/assets/7942491/10410521/9e96b05e-6f4c-11e5-9e83-b163a7b84f89.PNG)

**Comment by mwashinsky** [comment]
Hi I am also getting the following error when trying to install the module. please help.
![error](https://cloud.githubusercontent.com/assets/5296227/10476960/e5f46c5a-725a-11e5-8a22-7a6e155f506e.png)

**Comment by JayVora-SerpentCS** [comment]
Working on it, for v9!
v8, has no error,please detail the step..and paste the text plz

**Comment by mwashinsky** [comment]
I downloaded the module from the odoo site and not from github. I downloaded the one from here and it works fine

**Comment by JayVora-SerpentCS** [comment]
Thanks.
