### ISSUE TITLE
error in installation 

### ISSUE THREAD

**Issue by mwashinsky** [JayVora-SerpentCS/hotelmgmt_v8#28]
Hi I managed to get hotel management module in my apps list and went ahead to install it.although I see no error screened it is stuck at this point.see attached image
![error 2](https://cloud.githubusercontent.com/assets/5296227/10519581/fef75964-736e-11e5-9a93-aa7531a7de46.png)

**Comment by mwashinsky** [comment]
Please anyone for help on this?

**Comment by lambone** [comment]
any error log？

**Comment by JayVora-SerpentCS** [comment]
Please show the log, will helpus.
