### ISSUE TITLE
Error Creating Invoice

### ISSUE THREAD

**Issue by DarioLodeiros** [JayVora-SerpentCS/hotelmgmt_v8#29]
Creating invoice from a service details, i get the next issue:
"'hotel.folio' object has no attribute 'folio_pos_order_ids'" while evaluating
u'action_invoice_create()'

**Comment by DarioLodeiros** [comment]
I think I found the problem
It seems that the hotel module has a dependecy with Hotel POS restaurant Management...  since this module is the one that creates the field 'foilio_pos_order_ids'.

**Comment by SerpentCS** [comment]
Hello darkidlv,
We have made required changes and upgraded the code.
Please pull the latest code, it will work for you.
Thanks for using our repository.
