### ISSUE TITLE
installing Hotel Mgmt on V9

### ISSUE THREAD

**Issue by iamtutumo** [JayVora-SerpentCS/hotelmgmt_v8#32]
I get this error
![11](https://cloud.githubusercontent.com/assets/7942491/10903907/c23fc258-821f-11e5-834a-93310c65e31e.PNG)
 when i try to install on V9

**Comment by JayVora-SerpentCS** [comment]
Latest https://github.com/JayVora-SerpentCS/hotelmgmt_v8/tree/9.0 might fix
