### ISSUE TITLE
Restautant : integration with  point of sale

### ISSUE THREAD

**Issue by mslokhat** [JayVora-SerpentCS/hotelmgmt_v8#38]
Hi,
it would be a good idea to integrate the orders inside the restaurant point of sale

imagine an hotel having his own restaurant which receive both hotel customers and external clients.

another usage : Point of sale for the SPA 

Rgds

**Comment by JayVora-SerpentCS** [comment]
@mslokhat , we already have pos module linking to hotel.

**Comment by JayVora-SerpentCS** [comment]
Any service (external or internal customers) can be linked.
