### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by Paul-Birnbaum** [JayVora-SerpentCS/hotelmgmt_v8#4]
Hello i am trying to install it by cloning the repo in my openerp addons folder, then log out restart opener and no way to find it in the module

Best regards

Paul

**Comment by jwcaceres** [comment]
Hi, i'm trying to install in Openerp 7 (Debian OS) so i have this message:

'report_extended' that depends on the module 'report'.
The latter module is not available on your system.

can any body helpme, please?

**Comment by JayVora-SerpentCS** [comment]
You must use the v7 source from https://code.launchpad.net/~serpentcs/hotel-management-system/hotel-7.0.
Thanks.

**Comment by jwcaceres** [comment]
Thanks JayVora, I downloaded this source but when i install in openerp i have this error:

Exception: Module loading hotel failed: file hotel/security/ir.model.access.csv could not be processed:
Line 4 : No matching record found for external id 'model_room_rent' in field 'Object'

Could you helpme, please ?
