### ISSUE TITLE
How can I cancel a hotel reservation?

### ISSUE THREAD

**Issue by mrbrazzi** [JayVora-SerpentCS/hotelmgmt_v8#42]
Hi, I'm testing the hotel_reservation module, I can't find a button to cancel hotel_reservation, but in states area where the Cancel status exist but, how can I cancel it?

Best regards

**Comment by ghost** [comment]
@mrbrazzi Thanks for the report !
We shall check and revert you asap.

**Comment by mrbrazzi** [comment]
It's possible to add a "Renew" state where I can renew (put in draft again) a reservation from a cancel state?
