### ISSUE TITLE
Cancelled reservations appears in Room Reservation Summary

### ISSUE THREAD

**Issue by mrbrazzi** [JayVora-SerpentCS/hotelmgmt_v8#45]
When I cancel a reservation it still appears in Room Reservation Summary. 

Only if I delete the Room Reservation Line in the Room object it disappear in the Room Reserveration Summary.

Also, if I delete the object Hotel Reservation using the tree view delete action that does not delete the Room Reservation Line.

Here you can find steps followed:
![1-reservations - odoo 2015-12-30 16-19-28](https://cloud.githubusercontent.com/assets/1132397/12057743/01d5b282-af12-11e5-8865-dcb13efba210.png)

![2-room reservations summary - odoo 2015-12-30 16-19-59](https://cloud.githubusercontent.com/assets/1132397/12057739/01b1221e-af12-11e5-9b32-446d17345d9e.png)

![3-reservations - odoo 2015-12-30 16-20-33](https://cloud.githubusercontent.com/assets/1132397/12057741/01c692b6-af12-11e5-966a-955048f08542.png)

![4-room reservations summary - odoo 2015-12-30 16-23-11](https://cloud.githubusercontent.com/assets/1132397/12057740/01b9fdd0-af12-11e5-8375-564a0ab270e4.png)

![5-hotel room - odoo 2015-12-30 16-23-43](https://cloud.githubusercontent.com/assets/1132397/12057742/01d0805a-af12-11e5-9e0c-9ef769d1d369.png)

![6-hotel room - odoo 2015-12-30 16-30-33](https://cloud.githubusercontent.com/assets/1132397/12057804/d62355bc-af12-11e5-924b-e689b6c8e817.png)

![7-room reservations summary - odoo 2015-12-30 16-31-31](https://cloud.githubusercontent.com/assets/1132397/12057805/d62bba90-af12-11e5-9a4b-c8919d889eca.png)

Best regards

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/hotelmgmt_v8/commit/485a26efd0d00586ed891c19eaa5159a896b64c1 fixes it!
