### ISSUE TITLE
After creating KOT, Table order not setting to done state

### ISSUE THREAD

**Issue by ravik786** [JayVora-SerpentCS/hotelmgmt_v8#46]
In hotel management module (using odoo-9 community edition on windows), As After creating KOT I am trying to set table order to done but system giving the following error.

https://web.facebook.com/photo.php?fbid=883282295125569&set=pcb.1771575246399623&type=3&relevant_count=2

**Comment by JayVora-SerpentCS** [comment]
Ravi, it says you have to add UoM. Either the uom is not entered, or not pulled through.

**Comment by JayVora-SerpentCS** [comment]
https://github.com/JayVora-SerpentCS/hotelmgmt_v8/commit/485a26efd0d00586ed891c19eaa5159a896b64c1
