### ISSUE TITLE
Uncaught Error: QWeb2: Template 'summaryDetails' not found

### ISSUE THREAD

**Issue by stellaf** [JayVora-SerpentCS/hotelmgmt_v8#56]
Uncaught Error: QWeb2: Template 'summaryDetails' not found. 
when I click on the "Reservation summary" or "Hotel frontdesk board".

Newly installed hotelmgmt version 9, in odoo 9, centos 7.

**Comment by odaybari** [comment]
Had the same error but all worked fin after system reboot. 
Hop this help

**Comment by marcosmamg** [comment]
I can confirm that restarting the Odoo service fixes the problem.

**Comment by OmanGhost** [comment]
Restart Odoo service solve my problem, Thank you mates.
