### ISSUE TITLE
Confirmed Reservation Cannot be cancelled.

### ISSUE THREAD

**Issue by mikeross6233m** [JayVora-SerpentCS/hotelmgmt_v8#60]
In new updated module, there is no option to cancel the confirmed reservations

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello Mikeross,

When you click the cancel reservation button then cancel the reservation when it is confirm state
Shows below link
![r 00012 odoo](https://cloud.githubusercontent.com/assets/23502495/21709749/7f473a02-d409-11e6-9624-d1d520302f97.png)

**Comment by JayVora-SerpentCS** [comment]
@mikeross6233m please share us more info in case you have a traceback or a blocker. We will take a look and fix once encountered. Meanwhile, I am closing this,
