### ISSUE TITLE
Table Order Cancellation is not happening

### ISSUE THREAD

**Issue by mikeross6233m** [JayVora-SerpentCS/hotelmgmt_v8#61]
Suppose in case a customer orders two items and after the KOT generation cancels the first item but keeps the second item in order, then how the kitchen will know that the first item is cancelled but not the second one.
There is facility provided to let kitchen know that some order is cancelled.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
When we cancel the order then order is gone draft state and both items are cancelled because od whole KOT is cancelled in Table Order
