### ISSUE TITLE
Folio status is not showing done.

### ISSUE THREAD

**Issue by mikeross6233m** [JayVora-SerpentCS/hotelmgmt_v8#63]
In Generate Folio, after confirming the folio and successful payment in invoicing the status of folio still remains "sales order" where it should be "done" instead.

Even after the customer checks out, new table order can be generated on that folio number which should not happen.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
When Folio is done state then it takes locked state integration of V10
 See the Screen shot
![folio 00001 odoo](https://cloud.githubusercontent.com/assets/23502495/21709301/f8a90b04-d405-11e6-9cc2-8cde36939d6e.png)
