### ISSUE TITLE
Pos Orders not shown in Folio

### ISSUE THREAD

**Issue by marcosmamg** [JayVora-SerpentCS/hotelmgmt_v8#74]
When creating orders using POS touch interface these are not shown on the folio.
Only orders created using the form is showing. Are only payed orders shown on the folio?

Please refer to the attachments to verify what I am saying. 
Folio is showing order Main/0010 but not Main/0011 which is the one I created using the POS touch interface.
![posinterface](https://cloud.githubusercontent.com/assets/1951032/19712679/348b0b5a-9afd-11e6-87d3-8e7b37927ed6.PNG)
![posorder](https://cloud.githubusercontent.com/assets/1951032/19712677/34872ce2-9afd-11e6-98e1-403e3a525671.PNG)
![folio](https://cloud.githubusercontent.com/assets/1951032/19712678/348a107e-9afd-11e6-8afd-a1ba216fb353.PNG)

**Comment by SerpentCS** [comment]
Dear Marcosmamg, 

From POS Interface we couldn't did integration of POS Order to Folio, As of now from POS Form alone we can achieve this feature.

**Comment by marcosmamg** [comment]
I appreciate your answer, what is the reason of that missing integration, is there any hint you might provide?

**Comment by KrishnaPrajapati-SerpentCS** [comment]
In POS Interface we could not did integration of the POS order to folio. Ok

**Comment by JayVora-SerpentCS** [comment]
We have worked on this feature and in the next week, you will have this feature there!
