### ISSUE TITLE
[10.0] Reservations Summary not working: this.destroy_content is not a function

### ISSUE THREAD

**Issue by explanar** [JayVora-SerpentCS/hotelmgmt_v8#82]
`TypeError: this.destroy_content is not a function`

    `at Class.renderElement ( /web/content/903-878ce70/web.assets_backend.js:3196:473)
    at  /web/content/353-0c3fb32/web.assets_common.js:3112:917
    at  /web/content/353-0c3fb32/web.assets_common.js:547:681
    at fire ( /web/content/353-0c3fb32/web.assets_common.js:541:299)
    at Object.add [as done] ( /web/content/353-0c3fb32/web.assets_common.js:542:467)
    at Array.<anonymous> ( /web/content/353-0c3fb32/web.assets_common.js:547:649)
    at Function.each ( /web/content/353-0c3fb32/web.assets_common.js:370:767)
    at Object.<anonymous> ( /web/content/353-0c3fb32/web.assets_common.js:547:560)
    at Function.Deferred ( /web/content/353-0c3fb32/web.assets_common.js:548:194)
    at Object.then ( /web/content/353-0c3fb32/web.assets_common.js:547:525)`

**Different behaviour Res. Summary vs. FrontDesk Board**
FrontDesk Board loads and shows up behind error message, 
Reservation Summary shows nothing.

**installed modules:**
hotel
hotel_reservation
report_hotel_reservation
board_frontdesk
hotel_pos_restaurant
hotel_restaurant

**Odoo Version:**
10.0 community clean install
ubuntu 16.04 server minimal, updated

**Additional error in FrontDesk Board:**
When folding "Currently Reserved Tables Details"

` /web/content/903-878ce70/web.assets_backend.js:2907
    TypeError: Cannot set property 'fold' of undefined`

    at Class.on_fold_action ( /web/content/903-878ce70/web.assets_backend.js:2907:359)
    at HTMLSpanElement.<anonymous> ( /web/content/353-0c3fb32/web.assets_common.js:3126:11)
    at HTMLDivElement.dispatch ( /web/content/353-0c3fb32/web.assets_common.js:637:451)
    at HTMLDivElement.elemData.handle ( /web/content/353-0c3fb32/web.assets_common.js:610:173)`

Only one Date is shown in Reservations calendar, Rooms are occupied immediately after reservation in the future - if a reservation for tomorrow is confirmed, Room shows occupied today.

**Comment by seanboyce** [comment]
Hello, I also experienced this issue.

I went opened up hotel_reservation/static/src/js/hotel_room_summary.js and commented out the 2 instances where the function this.destroy_content() is called. 

The result is that the reservations summary screen no longer raises an error. It doesn't seem to work properly either -- but when the reservations summary is opened via the Hotel FrontDesk Board it DOES work for me, without errors!

Previously, it worked from the Hotel FrontDesk Board, but would raise an error, I would lose the ability to log out of odoo, and the reservations summary data would be 'stuck' behind every screen loaded thereafter. Fixing this previously required a reset of odoo from the command line, going to the top level page (domain.com:8069) logging out from there, and then logging in again.

So not really a fix but did resolve some of the more serious issues I had. Looking at hotel_room_summary.js, it really looks like there is no function called destroy_content defined or included though. I tried to guess what it would do and implement it but my knowledge in this area is not very good and I didn't meet any success.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
this.destroy_content() is called when quick hotel reservation summary view and It shows free room and assigned room by the customer

![room reservations summary odoo](https://cloud.githubusercontent.com/assets/23502495/21670881/bbe51f5a-d33d-11e6-8f46-8a38b82d9810.png)

**Comment by JayVora-SerpentCS** [comment]
With the latest source code, it is fixed. Would you please recheck?
Thanks.

**Comment by seanboyce** [comment]
Hello,
I tried with the latest source code and can confirm that the issue is resolved.
Previously I had downloaded your application from: https://www.odoo.com/apps/modules/10.0/hotel/
Thank you for your time and an excellent application!

**Comment by JayVora-SerpentCS** [comment]
Thank you @seanboyce , can I have your email Id to communicate with you?
