### ISSUE TITLE
error when click.. Hotel Mngmt >> Reservations >> Reservations Summary

### ISSUE THREAD

**Issue by evansadji** [JayVora-SerpentCS/hotelmgmt_v8#83]
![screenshot 2017-01-02 20 52 50](https://cloud.githubusercontent.com/assets/10150411/21590328/7de06816-d12d-11e6-92de-f6d4722e9a90.png)

**Comment by JayVora-SerpentCS** [comment]
@evansadji Please elaborate the steps, this is on which version?

**Comment by evansadji** [comment]
Hai JayVora
Appologize..I forgot to mention .. It is on version 10.0
Warm regardsE.Adji


Sent from my Samsung device

-------- Original message --------

**Comment by JayVora-SerpentCS** [comment]
Steps please.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Its working on version 10.0
See the Reservation Summary
![room reservations summary odoo](https://cloud.githubusercontent.com/assets/23502495/21708693/1d06b032-d401-11e6-8c28-649cc59790d8.png)

**Comment by evansadji** [comment]
Hai JayVora..

Yes its working now..
i just took your below link from github..
https://github.com/JayVora-SerpentCS/OdooHotelManagementSystem/tree/10.0

Thanks a bunch

**Comment by evansadji** [comment]
Hai jayVora..
I notice NOW .. on Hotel Management --> Food Item --> Food Items
it looks messy .. any idea how to fixed it..

Thanks

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello Sir

Hotel Management --> Food Item --> Food Items
I solve the issues.

Thank You

**Comment by evansadji** [comment]
Hello JayVora
i am looking for booking web font-end.. does it exist already ?

Thank you

**Comment by JayVora-SerpentCS** [comment]
Kindly provide us your email id, or mail to contact@serpentcs.com, we can have a discussion over this.
