### ISSUE TITLE
Room Not available for booking in next date and time

### ISSUE THREAD

**Issue by Syedmudassar** [JayVora-SerpentCS/hotelmgmt_v8#88]
Once we booked the room then it is not available for booking in future dates

**Comment by JayVora-SerpentCS** [comment]
@krishnaprajapati16894 please check this concern.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Once we booked the room then it is available for booking in future dates
Here When I assigned room at 25/04/2017
![4](https://cloud.githubusercontent.com/assets/23502495/25378704/793e1e36-29c8-11e7-8db2-be173c2c99a5.png)
And here I assigned same room as future date like 26/4/2017 to 28/04/2017.
![5](https://cloud.githubusercontent.com/assets/23502495/25378775/ad5acfca-29c8-11e7-9394-49c9ecf2ea6e.png)
