### ISSUE TITLE
Problem while creating a new reservation

### ISSUE THREAD

**Issue by LF2T** [JayVora-SerpentCS/hotelmgmt_v8#89]
Hello guys,
Every time I try to create  a new reservation it gives this error : 

 File "C:\Users\Ismail\workspace\odoo-8.0-20160916\openerp\addons\hotel_reservation\models\hotel_reservation.py", line 321, in set_to_draft_reservation
    self.delete_workflow(cr, uid, [reservation.id])
ValueError: "global name 'cr' is not defined" while evaluating
u'set_to_draft_reservation()'

even when i try to update the module with demo data it gives : 

ValueError: "global name 'cr' is not defined" while evaluating

Thnx

**Comment by JayVora-SerpentCS** [comment]
@LF2T It has been fixed, thanks.
