### ISSUE TITLE
Can not create Rooms (Ubuntu 14.04 64 - Odoo 8)

### ISSUE THREAD

**Issue by malonsopraxya** [JayVora-SerpentCS/hotelmgmt_v8#9]
Hi all.

Recently I perform a fresh install of Odoo 8 in Ubuntu 14.04 x86_64. After that I perform the installation of several modules: Accounting, Sales, Purchases, MRP, Projects, POS, WH, HR, CRM...

My user is a super user with all permissions, is a copy of Admin user.

Now I'm trying to check out Hotel Management module. I've got some issues installing this module, mainly solved Updating the module (¿? can't understand why...). Then I set my user as Hotel Manager and Hotel User, so everything seems to be OK.

Now I open room list from Hotel Management / Configuration / Room / Rooms to create a room.
I press the Create button, give 101 in Name field and press Save. The following error raises:

![screenshot_2015-05-13_13-26-47](https://cloud.githubusercontent.com/assets/12210527/7609510/c5c0e6d0-f973-11e4-97e9-d100e343ca7c.png)

Please, ideas will be welcome.

Kind regards.

**Comment by JayVora-SerpentCS** [comment]
Please try out with the latest code.
Thanks,
