### ISSUE TITLE
Hotel Room Rent Settings 

### ISSUE THREAD

**Issue by syedimranshah** [JayVora-SerpentCS/hotelmgmt_v8#91]
Hello and good day

Unit of Sale in odoo 9 Rooms module exists but in 10 its not available so when creating reservation and then folio it shows 0 total amount that is causing issues ..... if removal was due to some reason please help in setting it up correctly

**Comment by JayVora-SerpentCS** [comment]
@syedimranshah this change has been introduced in core v10 module of sales. You have to be in a group of Unit of sales. product_uom is the field used -Unit of Measure.

**Comment by JayVora-SerpentCS** [comment]
The group you must be in is... 'Manage Multiple Units of Measure'
