### ISSUE TITLE
How Can I make a Group Reservation

### ISSUE THREAD

**Issue by AizenL** [JayVora-SerpentCS/hotelmgmt_v8#92]
Hi, please some one can explain me how to make a Group Reservation? Thanks in advance.

**Comment by JayVora-SerpentCS** [comment]
Did you mean you want to reserve more rooms at the same time ?You can do!

**Comment by AizenL** [comment]
Hi, thanks for taking your time to answer me. I mean if a company can make multiple reservations for their contacts. Or if every contact can have multiple folios. or if I can merge different folios?

**Comment by AizenL** [comment]
FYI

**Comment by JayVora-SerpentCS** [comment]
for now, we haven't added the merge folio feature.
Thanks for the report, we will plan an action for it.

**Comment by JayVora-SerpentCS** [comment]
We've added into the wiki.https://github.com/JayVora-SerpentCS/OdooHotelManagementSystem/wiki
