### ISSUE TITLE
Rent field in Room Lines in folio always zero

### ISSUE THREAD

**Issue by anglovina** [JayVora-SerpentCS/hotelmgmt_v8#99]
Hi, i'm in testing this module in odoo v10 by using demo data and it giving error. I think that your demo data has **different format date** in _/hotel_restaurant/views/hotel_restaurant_data.xml_
![error install](https://cloud.githubusercontent.com/assets/27417576/25001736/0f7c9c1c-2071-11e7-82dd-c2e4883f9973.png)

Then,
When i click "_Create Folio_", the **rent** field in **Room Lines** in Folio is still zero.
Is it fill manually or automatically?
If it auto fill, when it will filled ?
here is my reservation form
![reserv](https://cloud.githubusercontent.com/assets/27417576/25001776/3a56c00c-2071-11e7-84d0-a5409276bfa3.png)

and it is my folio
![folio](https://cloud.githubusercontent.com/assets/27417576/25001798/5311a7ec-2071-11e7-8ddf-af4cfaacd549.png)

They are my setting rooms
![roomdlm](https://cloud.githubusercontent.com/assets/27417576/25001820/69fa5dbe-2071-11e7-84c5-4cdb5d852e68.png)
![room](https://cloud.githubusercontent.com/assets/27417576/25001821/69fb7cb2-2071-11e7-8964-9b3240a1dd83.png)

**Comment by KrishnaPrajapati-SerpentCS** [comment]
When I am testing this module in odoo v10 by using demo data then that does not give any error with hotel_restaurant/views/hotel_restaurant_data.xml file

**Comment by KrishnaPrajapati-SerpentCS** [comment]
When i click "Create Folio", the rent field in Room Lines in Folio is as per room sale price
Here is my reservation form
![1](https://cloud.githubusercontent.com/assets/23502495/25378054/d8e9e98e-29c6-11e7-8cc9-070c778af5ad.png)

And its is my folio form : To see this change the room rate value 
![2](https://cloud.githubusercontent.com/assets/23502495/25378126/0e97aefe-29c7-11e7-859e-6768e3e8ef36.png)

**Comment by JayVora-SerpentCS** [comment]
We are closing it for now. Let us know if the issue persists. We will reopen it.
